version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: vollmed_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123asd456zxC**'
      MYSQL_DATABASE: 'vollmed_api'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: